import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Boxes, Check, CircleDollarSign, ShoppingBag, Store, UsersRound, X } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { formatCurrency } from "@/lib/utils";
import { updateShopStatusAction } from "../actions/admin";

export const metadata: Metadata = { title: "Platform Admin | BabulShop" };
export const dynamic = "force-dynamic";

type Transaction = { amount?: number | string | null; platform_fee?: number | string | null; created_at?: string | null };
type PendingShop = { id: string; name?: string | null; slug?: string | null; created_at?: string | null };

export default async function AdminPage() {
  const supabase = await createClient();
  const [orders, shops, profiles, categories, transactions, pendingResponse] = await Promise.all([
    supabase.from("orders").select("id", { count: "exact", head: true }),
    supabase.from("shops").select("id", { count: "exact", head: true }).eq("status", "active"),
    supabase.from("profiles").select("id", { count: "exact", head: true }),
    supabase.from("categories").select("id", { count: "exact", head: true }),
    supabase.from("transactions").select("amount, platform_fee, created_at").eq("status", "completed").order("created_at", { ascending: false }).limit(1000),
    supabase.from("shops").select("id, name, slug, created_at", { count: "exact" }).eq("status", "pending").order("created_at", { ascending: false }).limit(6),
  ]);
  const rows = (transactions.data ?? []) as Transaction[];
  const pendingShops = (pendingResponse.data ?? []) as PendingShop[];
  const volume = rows.reduce((sum, row) => sum + Number(row.amount ?? 0), 0);
  const revenue = rows.reduce((sum, row) => sum + Number(row.platform_fee ?? 0), 0);
  return <div className="mx-auto max-w-[1440px] p-5 sm:p-8">
    <header className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[11px] font-black uppercase tracking-[.18em] text-orange-500">BabulShop control room</p><h1 className="mt-2 text-4xl font-black tracking-[-.055em]">Platform overview</h1><p className="mt-2 text-sm text-slate-500">Marketplace health, sales, and vendor requests at a glance.</p></div><Link href="/admin/shops?status=pending" className="button-primary bg-orange-500 hover:bg-orange-600">Review requests <ArrowRight className="size-4" /></Link></header>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={CircleDollarSign} label="Gross volume" value={formatCurrency(volume)} detail="Completed transactions" /><MetricCard icon={CircleDollarSign} label="Platform revenue" value={formatCurrency(revenue)} detail="Fees collected" tone="text-emerald-600" /><MetricCard icon={Store} label="Active shops" value={shops.count ?? 0} detail="Currently selling" /><MetricCard icon={ShoppingBag} label="Total orders" value={orders.count ?? 0} detail="Across the platform" /></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_.8fr]"><SalesChart points={buildChart(rows)} /><section className="surface p-6"><div className="flex items-start justify-between"><div><p className="text-[11px] font-black uppercase tracking-[.16em] text-orange-500">Platform snapshot</p><h2 className="mt-1 text-xl font-black">System health</h2></div><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10"><Store className="size-5" /></span></div><div className="mt-6 space-y-4"><SnapshotRow label="Categories" value={categories.count ?? 0} icon={Boxes} /><SnapshotRow label="Registered users" value={profiles.count ?? 0} icon={UsersRound} /><SnapshotRow label="Pending requests" value={pendingResponse.count ?? pendingShops.length} icon={Store} /></div><div className="mt-6 flex items-center gap-2 border-t border-slate-100 pt-5 text-xs font-bold text-emerald-600 dark:border-white/10"><span className="size-2 rounded-full bg-emerald-500" /> All systems operational</div></section></section>
    <section className="surface mt-6 overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-6 dark:border-white/10"><div><p className="text-[11px] font-black uppercase tracking-[.16em] text-orange-500">Needs your attention</p><h2 className="mt-1 text-xl font-black">Pending shop requests</h2></div><Link href="/admin/shops?status=pending" className="flex items-center gap-1 text-xs font-bold text-slate-500 hover:text-orange-500">View all <ArrowRight className="size-4" /></Link></div>{pendingShops.length === 0 ? <p className="p-10 text-center text-sm text-slate-500">No pending shop requests right now.</p> : <div className="divide-y dark:divide-white/10">{pendingShops.map((shop) => <div key={shop.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-extrabold">{shop.name ?? "Unnamed shop"}</h3><p className="mt-1 text-xs text-slate-500">BabulShop.com/shop/{shop.slug} · {shop.created_at ? new Date(shop.created_at).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }) : "Recently requested"}</p></div><div className="flex gap-2"><form action={async () => { "use server"; await updateShopStatusAction(shop.id, "active"); }}><button className="button-secondary text-emerald-700"><Check className="size-4" /> Approve</button></form><form action={async () => { "use server"; await updateShopStatusAction(shop.id, "rejected"); }}><button className="button-secondary text-rose-700"><X className="size-4" /> Reject</button></form></div></div>)}</div>}</section>
  </div>;
}

function buildChart(rows: Transaction[]) { const today = new Date(); return Array.from({ length: 7 }, (_, index) => { const date = new Date(today); date.setHours(0, 0, 0, 0); date.setDate(today.getDate() - (6 - index)); const key = date.toISOString().slice(0, 10); return { label: date.toLocaleDateString("en-US", { weekday: "short" }), amount: rows.filter((row) => row.created_at?.slice(0, 10) === key).reduce((sum, row) => sum + Number(row.amount ?? 0), 0) }; }); }
function SalesChart({ points }: { points: Array<{ label: string; amount: number }> }) { const max = Math.max(...points.map((point) => point.amount), 1); return <section className="surface p-6 sm:p-7"><div className="flex items-start justify-between gap-3"><div><p className="text-[11px] font-black uppercase tracking-[.16em] text-orange-500">Sales activity</p><h2 className="mt-1 text-xl font-black">Gross volume · last 7 days</h2></div><span className="rounded-full bg-orange-50 px-3 py-1.5 text-[11px] font-bold text-orange-600 dark:bg-orange-500/10 dark:text-orange-300">Live data</span></div><div className="mt-8 flex h-56 items-end gap-2 border-b border-slate-200 sm:gap-4 dark:border-white/10">{points.map((point) => <div key={point.label} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><div className="group relative flex h-full w-full items-end"><div className="w-full rounded-t-xl bg-orange-400 transition hover:bg-orange-500" style={{ height: `${Math.max((point.amount / max) * 100, point.amount ? 8 : 2)}%` }}><span className="pointer-events-none absolute -top-8 left-1/2 hidden -translate-x-1/2 whitespace-nowrap rounded-lg bg-slate-900 px-2 py-1 text-[10px] font-bold text-white group-hover:block">{formatCurrency(point.amount)}</span></div></div><span className="text-[10px] font-bold text-slate-400">{point.label}</span></div>)}</div><div className="mt-4 flex justify-between text-[10px] font-bold uppercase tracking-[.12em] text-slate-400"><span>Activity by day</span><span>{formatCurrency(points.reduce((sum, point) => sum + point.amount, 0))} total</span></div></section>; }
function MetricCard({ icon: Icon, label, value, detail, tone }: { icon: typeof CircleDollarSign; label: string; value: string | number; detail: string; tone?: string }) { return <div className="surface p-5"><div className="flex items-start justify-between gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-orange-50 text-orange-500 dark:bg-orange-500/10"><Icon className="size-5" /></span><span className="text-[10px] font-black uppercase tracking-[.12em] text-emerald-500">Live</span></div><p className="mt-5 text-xs font-bold text-slate-500">{label}</p><p className={`mt-1 text-2xl font-black tracking-[-.04em] ${tone ?? ""}`}>{value}</p><p className="mt-1 text-[11px] text-slate-400">{detail}</p></div>; }
function SnapshotRow({ label, value, icon: Icon }: { label: string; value: number; icon: typeof Boxes }) { return <div className="flex items-center justify-between"><span className="flex items-center gap-3 text-sm font-semibold text-slate-500"><Icon className="size-4 text-orange-500" />{label}</span><strong className="text-lg font-black">{value}</strong></div>; }
