"use client";

import Link from "next/link";
/* eslint-disable @next/next/no-img-element */
import { useState } from "react";
import { ArrowLeft, CheckCircle2, CircleDollarSign, Clock3, ExternalLink, Package, Pause, Play, ShoppingCart, Star, Store, Users } from "lucide-react";
import { toast } from "sonner";
import { updateShopStatusAction } from "@/app/actions/admin";
import { formatCurrency } from "@/lib/utils";

type Row = Record<string, unknown>;
type ShopDetails = { shop: Row; products: Row[]; orders: Row[]; customers: Row[]; payouts: Row[]; reviews: Row[]; members: Row[]; owner: Row | null; orderItems: Row[]; performance: { label: string; sales: number; orders: number }[] };

const tabs = ["Overview", "Products", "Orders", "Earnings", "Payouts", "Reviews"];
const statusStyles: Record<string, string> = { active: "bg-emerald-50 text-emerald-700", suspended: "bg-rose-50 text-rose-700", pending: "bg-orange-50 text-orange-700", rejected: "bg-slate-100 text-slate-600" };
function text(row: Row | null | undefined, ...keys: string[]) { return String(keys.map((key) => row?.[key]).find((value) => value !== undefined && value !== null && value !== "") ?? "-"); }
function number(row: Row | null | undefined, ...keys: string[]) { return Number(keys.map((key) => row?.[key]).find((value) => value !== undefined && value !== null && value !== "") ?? 0); }
function date(value: unknown) { return value ? new Date(String(value)).toLocaleDateString() : "-"; }
function orderStatus(order: Row) { return text(order, "order_status", "status").toLowerCase(); }
function customerName(row: Row | null | undefined) { const direct = text(row, "full_name", "name", "display_name", "username", "owner_name", "customer_name"); if (direct !== "-") return direct; const first = text(row, "first_name"); const last = text(row, "last_name"); return [first, last].filter((value) => value !== "-").join(" ") || text(row, "email", "owner_email", "user_id"); }
function Badge({ value }: { value: string }) { return <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-wide ${statusStyles[value.toLowerCase()] ?? "bg-slate-100 text-slate-600"}`}>{value}</span>; }
function Empty({ children }: { children: string }) { return <div className="surface p-12 text-center text-sm text-slate-500">{children}</div>; }
function Stat({ icon: Icon, label, value }: { icon: typeof Store; label: string; value: string | number }) { return <div className="surface p-5"><Icon className="size-5 text-orange-500" /><p className="mt-4 text-xs font-bold text-slate-500">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>; }
function ShopLogo({ shop }: { shop: Row }) { const [imageFailed, setImageFailed] = useState(false); const logo = text(shop, "logo_url", "logo"); return <span className="grid size-16 shrink-0 place-items-center overflow-hidden rounded-2xl bg-orange-50 text-orange-500 dark:bg-orange-500/10">{logo !== "-" && !imageFailed ? <img src={logo} alt={`${text(shop, "name")} logo`} className="size-full object-cover" onError={() => setImageFailed(true)} /> : <Store className="size-7" />}</span>; }

export function AdminShopDetails({ data }: { data: ShopDetails }) {
  const { shop, products, orders, customers, payouts, reviews, members, owner, orderItems, performance } = data;
  const [activeTab, setActiveTab] = useState("Overview");
  const [busy, setBusy] = useState(false);
  const status = text(shop, "status").toLowerCase();
  const grossSales = orders.filter((order) => ["delivered", "completed"].includes(orderStatus(order))).reduce((sum, order) => sum + number(order, "gross_amount", "total_amount", "subtotal", "total"), 0);
  const commission = orders.reduce((sum, order) => sum + number(order, "platform_commission"), 0);
  const net = orders.reduce((sum, order) => sum + number(order, "seller_earnings"), 0);
  const pending = orders.filter((order) => ["pending", "not_eligible"].includes(text(order, "payout_status").toLowerCase())).reduce((sum, order) => sum + number(order, "seller_earnings"), 0);
  const paid = payouts.filter((payout) => text(payout, "status").toLowerCase() === "paid").reduce((sum, payout) => sum + number(payout, "net_amount", "amount"), 0);
  const changeStatus = async () => {
    const nextStatus = status === "suspended" ? "active" : "suspended";
    if (!window.confirm(`${nextStatus === "suspended" ? "Suspend" : "Activate"} ${text(shop, "name")} ?`)) return;
    setBusy(true);
    const result = await updateShopStatusAction(String(shop.id), nextStatus);
    setBusy(false);
    if (result.success) { toast.success(`Shop ${nextStatus}`); window.location.reload(); } else toast.error(result.error ?? "Could not update shop");
  };
  return <div className="mx-auto max-w-[1400px] p-5 sm:p-8 lg:p-10">
    <Link href="/admin/shops" className="inline-flex items-center gap-1 text-xs font-bold text-slate-500 hover:text-orange-500"><ArrowLeft className="size-4" /> Shops</Link>
    <header className="mt-6 flex flex-col justify-between gap-5 border-b border-slate-200 pb-7 sm:flex-row sm:items-start dark:border-white/10"><div className="flex items-start gap-4"><ShopLogo shop={shop} /><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-black tracking-[-.05em]">{text(shop, "name")}</h1><Badge value={status} /></div><p className="mt-2 text-sm text-slate-500">/{text(shop, "slug")} · Created {date(shop.created_at)}</p><p className="mt-2 text-sm font-bold">Owner: {customerName(owner)}</p></div></div><div className="flex flex-wrap gap-2"><Link href={`/shop/${text(shop, "slug")}`} target="_blank" className="button-secondary"><ExternalLink className="size-4" /> Storefront</Link>{(status === "active" || status === "suspended") && <button type="button" disabled={busy} onClick={changeStatus} className={status === "active" ? "button-secondary text-rose-600" : "button-primary bg-emerald-600 hover:bg-emerald-700"}>{status === "active" ? <Pause className="size-4" /> : <Play className="size-4" />}{status === "active" ? "Suspend Shop" : "Activate Shop"}</button>}</div></header>
    <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><Stat icon={Package} label="Total products" value={products.length} /><Stat icon={ShoppingCart} label="Total orders" value={orders.length} /><Stat icon={CircleDollarSign} label="Total sales" value={formatCurrency(grossSales)} /><Stat icon={Users} label="Customers" value={customers.length} /><Stat icon={Clock3} label="Pending orders" value={orders.filter((order) => ["pending", "processing", "shipped"].includes(orderStatus(order))).length} /><Stat icon={CheckCircle2} label="Completed orders" value={orders.filter((order) => ["delivered", "completed"].includes(orderStatus(order))).length} /></section>
    <nav className="mt-8 flex gap-2 overflow-x-auto border-b border-slate-200 pb-2 dark:border-white/10">{tabs.map((tab) => <button key={tab} type="button" onClick={() => setActiveTab(tab)} className={`whitespace-nowrap rounded-t-lg px-3 py-2 text-xs font-black ${activeTab === tab ? "border-b-2 border-orange-500 text-orange-600" : "text-slate-500 hover:text-orange-500"}`}>{tab}</button>)}</nav>
    <main className="mt-6">{activeTab === "Overview" && <Overview shop={shop} owner={owner} products={products} customers={customers} performance={performance} />}{activeTab === "Products" && <Products products={products} />}{activeTab === "Orders" && <Orders orders={orders} customers={customers} orderItems={orderItems} />}{activeTab === "Earnings" && <Earnings orders={orders} grossSales={grossSales} commission={commission} net={net} pending={pending} paid={paid} />}{activeTab === "Payouts" && <Payouts payouts={payouts} orders={orders} />}{activeTab === "Reviews" && <Reviews reviews={reviews} />}</main>
  </div>;
}

function Overview({ shop, owner, products, customers, performance }: { shop: Row; owner: Row | null; products: Row[]; customers: Row[]; performance: AdminShopDetailsProps["data"]["performance"] }) { const max = Math.max(...performance.map((item) => item.sales), 0); return <div className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><section className="surface p-6"><h2 className="text-lg font-black">Shop information</h2><dl className="mt-5 space-y-4 text-sm"><Info label="Shop name" value={text(shop, "name")} /><Info label="Description" value={text(shop, "description")} /><Info label="Owner" value={customerName(owner)} /><Info label="Store URL" value={`/${text(shop, "slug")}`} /><Info label="Commission rate" value={`${number(shop, "commission_rate").toFixed(2)}%`} /><Info label="Payout hold" value={`${number(shop, "payout_hold_days")} days`} /><Info label="Created" value={date(shop.created_at)} /><Info label="Status" value={text(shop, "status")} /></dl></section><section className="surface p-6"><h2 className="text-lg font-black">Performance</h2>{performance.length === 0 ? <p className="mt-6 text-sm text-slate-500">Not enough historical order data to show a chart.</p> : <div className="mt-6 space-y-4">{performance.map((item) => <div key={item.label}><div className="flex justify-between text-xs font-bold"><span>{item.label}</span><span>{formatCurrency(item.sales)}</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-orange-500" style={{ width: `${max ? Math.max(4, item.sales / max * 100) : 4}%` }} /></div><p className="mt-1 text-[11px] text-slate-400">{item.orders} orders</p></div>)}</div>}<div className="mt-8 grid grid-cols-2 gap-4 border-t pt-5 text-sm"><Info label="Products" value={products.length} /><Info label="Customers" value={customers.length} /></div></section></div>; }
function Info({ label, value }: { label: string; value: string | number }) { return <div className="flex items-start justify-between gap-4 border-b border-slate-100 pb-3 dark:border-white/10"><span className="text-slate-500">{label}</span><strong className="max-w-[65%] text-right">{value}</strong></div>; }
function Products({ products }: { products: Row[] }) { return products.length === 0 ? <Empty>No products for this shop.</Empty> : <Table><thead><tr><th>Product</th><th>SKU</th><th>Price</th><th>Stock</th><th>Status</th><th>Featured</th><th>Created</th><th /></tr></thead><tbody>{products.map((product) => <tr key={text(product, "id")}><td className="font-bold">{text(product, "title", "name")}</td><td>{text(product, "sku")}</td><td>{formatCurrency(number(product, "price"))}</td><td>{number(product, "stock", "quantity")}</td><td><Badge value={text(product, "status", "is_active").replace("true", "active").replace("false", "inactive")} /></td><td>{number(product, "is_featured") ? "Yes" : "No"}</td><td>{date(product.created_at)}</td><td><Link className="text-xs font-black text-orange-600" href={`/admin/products/${text(product, "id")}/edit`}>View</Link></td></tr>)}</tbody></Table>; }
function Orders({ orders, customers, orderItems }: { orders: Row[]; customers: Row[]; orderItems: Row[] }) { const profiles = new Map(customers.map((customer) => [text(customer, "id"), customer])); return orders.length === 0 ? <Empty>No orders for this shop.</Empty> : <Table><thead><tr><th>Order ID</th><th>Customer</th><th>Date</th><th>Items</th><th>Subtotal</th><th>Shipping</th><th>Commission</th><th>Shop earnings</th><th>Status</th></tr></thead><tbody>{orders.map((order) => { const items = orderItems.filter((item) => text(item, "shop_order_id") === text(order, "id")); const customer = profiles.get(text(order, "customer_id", "user_id")); return <tr key={text(order, "id")}><td><Link className="font-bold text-orange-600" href={`/admin/orders?shopOrder=${text(order, "id")}`}>#{text(order, "id").slice(0, 8)}</Link></td><td>{customerName(customer) || text(order, "customer_id")}</td><td>{date(order.created_at)}</td><td>{items.reduce((sum, item) => sum + number(item, "quantity"), 0)}</td><td>{formatCurrency(number(order, "gross_amount", "subtotal", "total_amount"))}</td><td>{formatCurrency(number(order, "shipping_amount", "shipping"))}</td><td>{formatCurrency(number(order, "platform_commission"))}</td><td>{formatCurrency(number(order, "seller_earnings"))}</td><td><Badge value={orderStatus(order)} /></td></tr>})}</tbody></Table>; }
function Customers({ customers }: { customers: Row[] }) { return customers.length === 0 ? <Empty>No customers have purchased from this shop.</Empty> : <Table><thead><tr><th>Customer</th><th>Email</th><th>Total orders</th><th>Total spent</th><th>Last order</th><th>Status</th></tr></thead><tbody>{customers.map((customer) => <tr key={text(customer, "id")}><td className="font-bold">{customerName(customer)}</td><td>{text(customer, "email")}</td><td>{number(customer, "total_orders")}</td><td>{formatCurrency(number(customer, "total_spent"))}</td><td>{date(customer.last_order)}</td><td><Badge value={text(customer, "status", "customer_status")} /></td></tr>)}</tbody></Table>; }
function Earnings({ orders, grossSales, commission, net, pending, paid }: { orders: Row[]; grossSales: number; commission: number; net: number; pending: number; paid: number }) { return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat icon={CircleDollarSign} label="Gross sales" value={formatCurrency(grossSales)} /><Stat icon={CircleDollarSign} label="Commission" value={formatCurrency(commission)} /><Stat icon={CircleDollarSign} label="Net earnings" value={formatCurrency(net)} /><Stat icon={Clock3} label="Pending earnings" value={formatCurrency(pending)} /><Stat icon={CheckCircle2} label="Paid earnings" value={formatCurrency(paid)} /></div><Table><thead><tr><th>Order</th><th>Gross amount</th><th>Commission</th><th>Net amount</th><th>Status</th><th>Date</th></tr></thead><tbody>{orders.filter((order) => number(order, "gross_amount", "seller_earnings") > 0).map((order) => <tr key={text(order, "id")}><td className="font-bold">#{text(order, "id").slice(0, 8)}</td><td>{formatCurrency(number(order, "gross_amount"))}</td><td>{formatCurrency(number(order, "platform_commission"))}</td><td>{formatCurrency(number(order, "seller_earnings"))}</td><td><Badge value={text(order, "payout_status", "order_status")} /></td><td>{date(order.delivered_at ?? order.created_at)}</td></tr>)}</tbody></Table></div>; }
function Payouts({ payouts, orders }: { payouts: Row[]; orders: Row[] }) { const completed = orders.filter((order) => ["delivered", "completed"].includes(orderStatus(order))); return payouts.length === 0 ? completed.length === 0 ? <Empty>No payouts yet</Empty> : <section className="surface overflow-hidden"><div className="border-b border-slate-100 px-5 py-4 dark:border-white/10"><h2 className="font-black">Completed shop settlements</h2><p className="mt-1 text-xs text-slate-500">These completed shop orders have not produced a payout record yet.</p></div><Table><thead><tr><th>Shop order</th><th>Gross amount</th><th>Commission</th><th>Net amount</th><th>Completed</th><th>Status</th></tr></thead><tbody>{completed.map((order) => <tr key={text(order, "id")}><td className="font-bold">#{text(order, "id").slice(0, 8)}</td><td>{formatCurrency(number(order, "gross_amount"))}</td><td>{formatCurrency(number(order, "platform_commission"))}</td><td>{formatCurrency(number(order, "seller_earnings"))}</td><td>{date(order.delivered_at ?? order.created_at)}</td><td><Badge value={text(order, "payout_status", "pending")} /></td></tr>)}</tbody></Table></section> : <Table><thead><tr><th>Payout ID</th><th>Amount</th><th>Commission / deductions</th><th>Net payout</th><th>Date</th><th>Status</th></tr></thead><tbody>{payouts.map((payout) => <tr key={text(payout, "id")}><td className="font-bold">#{text(payout, "id").slice(0, 8)}</td><td>{formatCurrency(number(payout, "gross_amount"))}</td><td>{formatCurrency(number(payout, "commission_amount", "refund_amount"))}</td><td>{formatCurrency(number(payout, "net_amount", "amount"))}</td><td>{date(payout.paid_at ?? payout.created_at)}</td><td><Badge value={text(payout, "status")} /></td></tr>)}</tbody></Table>; }
function Reviews({ reviews }: { reviews: Row[] }) { return reviews.length === 0 ? <Empty>No reviews for this shop yet.</Empty> : <Table><thead><tr><th>Customer</th><th>Product</th><th>Rating</th><th>Review</th><th>Date</th><th>Approval</th></tr></thead><tbody>{reviews.map((review) => <tr key={text(review, "id")}><td>{customerName(review.customer as Row)}</td><td>{text(review.product as Row, "title", "name")}</td><td><span className="inline-flex items-center gap-1"><Star className="size-4 fill-amber-400 text-amber-400" />{number(review, "rating")}</span></td><td className="max-w-sm">{text(review, "review")}</td><td>{date(review.created_at)}</td><td><Badge value={text(review, "status")} /></td></tr>)}</tbody></Table>; }
function Members({ members }: { members: Row[] }) { return members.length === 0 ? <Empty>No members are associated with this shop.</Empty> : <Table><thead><tr><th>Member</th><th>Email</th><th>Role</th><th>Joined</th><th>Status</th></tr></thead><tbody>{members.map((member) => <tr key={text(member, "user_id")}><td className="font-bold">{customerName(member.profile as Row)}</td><td>{text(member.profile as Row, "email")}</td><td className="capitalize">{text(member, "role")}</td><td>{date(member.created_at)}</td><td><Badge value={text(member, "status", "member_status").replace("-", " ")} /></td></tr>)}</tbody></Table>; }
function Table({ children }: { children: React.ReactNode }) { return <section className="surface overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm [&_tbody]:divide-y [&_tbody]:divide-slate-100 [&_tbody]:dark:divide-white/10 [&_td]:px-5 [&_td]:py-4 [&_td]:align-top [&_td]:text-slate-600 [&_th]:border-b [&_th]:border-slate-100 [&_th]:bg-slate-50/80 [&_th]:px-5 [&_th]:py-4 [&_th]:text-[10px] [&_th]:font-black [&_th]:uppercase [&_th]:tracking-[.1em] [&_th]:text-slate-400 [&_th]:dark:border-white/10 [&_th]:dark:bg-white/5 [&_tr]:transition-colors [&_tbody_tr:hover]:bg-orange-50/40">{children}</table></div></section>; }

type AdminShopDetailsProps = { data: ShopDetails };
