"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Check, Edit3, Eye, Package, Plus, X } from "lucide-react";
import { toast } from "sonner";
import { updateAdminProductStatusAction } from "@/app/actions/admin";

type Product = { id: string; title: string; slug: string; price: number; status: string; createdAt: string };
type Tab = "all" | "pending" | "active" | "rejected";

export function AdminShopProductsTable({ shopId, products }: { shopId: string; products: Product[] }) {
  const [tab, setTab] = useState<Tab>("all");
  const [busy, setBusy] = useState<string | null>(null);
  const counts = { all: products.length, pending: products.filter((item) => item.status === "draft" || item.status === "pending").length, active: products.filter((item) => item.status === "published").length, rejected: products.filter((item) => item.status === "archived").length };
  const visible = useMemo(() => products.filter((item) => tab === "all" || (tab === "pending" ? ["draft", "pending"].includes(item.status) : tab === "active" ? item.status === "published" : item.status === "archived")), [products, tab]);
  async function setStatus(product: Product, status: "published" | "archived") { if (!window.confirm(`${status === "published" ? "Approve" : "Reject"} ${product.title}?`)) return; setBusy(product.id); const result = await updateAdminProductStatusAction(product.id, status); setBusy(null); if (result.success) { toast.success(status === "published" ? "Product approved" : "Product rejected"); window.location.reload(); } else toast.error(result.error ?? "Could not update product."); }
  return <div className="space-y-5"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div className="flex flex-wrap gap-2">{(["all", "pending", "active", "rejected"] as Tab[]).map((item) => <button type="button" key={item} onClick={() => setTab(item)} className={`rounded-xl px-3.5 py-2 text-xs font-black capitalize ${tab === item ? "bg-slate-950 text-white dark:bg-white dark:text-slate-950" : "bg-white text-slate-500 ring-1 ring-slate-200 dark:bg-white/5 dark:ring-white/10"}`}>{item === "pending" ? "Requests" : item} <span className="ml-1 opacity-60">{counts[item]}</span></button>)}</div><Link href={`/admin/products/new?shop=${shopId}`} className="button-primary bg-orange-500"><Plus className="size-4" /> Add product</Link></div><section className="surface overflow-hidden">{visible.length === 0 ? <div className="p-12 text-center"><Package className="mx-auto size-10 text-slate-300" /><p className="mt-3 text-sm text-slate-500">{tab === "pending" ? "No product requests" : "No products found"}</p></div> : <div className="divide-y divide-slate-100 dark:divide-white/10">{visible.map((product) => <div key={product.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-black">{product.title}</h2><p className="mt-1 text-xs text-slate-500">Rs {product.price.toLocaleString()} · Added {product.createdAt ? new Date(product.createdAt).toLocaleDateString() : "-"}</p><span className={`mt-2 inline-flex rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${product.status === "published" ? "bg-emerald-50 text-emerald-700" : product.status === "archived" ? "bg-rose-50 text-rose-700" : "bg-orange-50 text-orange-700"}`}>{product.status}</span></div><div className="flex flex-wrap gap-2"><Link href={`/product/${product.slug}`} target="_blank" className="button-secondary"><Eye className="size-4" /> View</Link><Link href={`/admin/products/${product.id}/edit`} className="button-secondary"><Edit3 className="size-4" /> Edit</Link>{product.status !== "published" && <button type="button" disabled={busy === product.id} onClick={() => setStatus(product, "published")} className="button-secondary text-emerald-700"><Check className="size-4" /> Approve</button>}{product.status !== "archived" && <button type="button" disabled={busy === product.id} onClick={() => setStatus(product, "archived")} className="button-secondary text-rose-700"><X className="size-4" /> Reject</button>}</div></div>)}</div>}</section></div>;
}
