"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Check, Edit3, Eye, MoreHorizontal, Package, Plus, X } from "lucide-react";
import { toast } from "sonner";
import { updateAdminProductStatusAction } from "@/app/actions/admin";
import { Pagination, useUrlPagination } from "@/components/ui/pagination";

type Product = { id: string; title: string; slug: string; price: number; stock: number; status: string; createdAt: string };
type Tab = "all" | "pending" | "active" | "rejected";

export function AdminShopProductsTable({ shopId, products }: { shopId: string; products: Product[] }) {
  const [tab, setTab] = useState<Tab>("all");
  const [busy, setBusy] = useState<string | null>(null);
  const [openMenu, setOpenMenu] = useState<string | null>(null);
  const counts = { all: products.length, pending: products.filter((item) => ["draft", "pending"].includes(item.status)).length, active: products.filter((item) => item.status === "published").length, rejected: products.filter((item) => item.status === "archived").length };
  const filtered = useMemo(() => products.filter((item) => tab === "all" || (tab === "pending" ? ["draft", "pending"].includes(item.status) : tab === "active" ? item.status === "published" : item.status === "archived")), [products, tab]);
  const pagination = useUrlPagination(filtered.length);
  const visible = filtered.slice(pagination.from, pagination.to + 1);
  async function setStatus(product: Product, status: "published" | "archived") { if (!window.confirm(`${status === "published" ? "Approve" : "Reject"} ${product.title}?`)) return; setBusy(product.id); const result = await updateAdminProductStatusAction(product.id, status); setBusy(null); if (result.success) { toast.success(status === "published" ? "Product approved" : "Product rejected"); window.location.reload(); } else toast.error(result.error ?? "Could not update product."); }































































































































































































































































































  return <div className="space-y-5"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div className="flex flex-wrap gap-2">{(["all", "pending", "active", "rejected"] as Tab[]).map((item) => <button type="button" key={item} onClick={() => { setTab(item); pagination.resetPage(); }} className={`rounded-xl px-3.5 py-2 text-xs font-black capitalize ${tab === item ? "bg-slate-950 text-white dark:bg-white dark:text-slate-950" : "bg-white text-slate-500 ring-1 ring-slate-200 dark:bg-white/5 dark:ring-white/10"}`}>{item === "pending" ? "Requests" : item} <span className="ml-1 opacity-60">{counts[item]}</span></button>)}</div><Link href={`/admin/products/new?shop=${shopId}`} className="button-primary bg-orange-500"><Plus className="size-4" /> Add product</Link></div><section data-pagination-list className={`surface overflow-hidden transition-opacity ${pagination.isPending ? "pointer-events-none opacity-60" : ""}`}>{visible.length === 0 ? <div className="p-12 text-center"><Package className="mx-auto size-10 text-slate-300" /><p className="mt-3 text-sm text-slate-500">{tab === "pending" ? "No product requests" : "No products found"}</p></div> : <div className="divide-y divide-slate-100 dark:divide-white/10">{visible.map((product) => <div key={product.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-black">{product.title}</h2><p className="mt-1 text-xs text-slate-500">Rs {product.price.toLocaleString()} · Stock {product.stock} · Added {product.createdAt ? new Date(product.createdAt).toLocaleDateString() : "-"}</p><span className={`mt-2 inline-flex rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${product.status === "published" ? "bg-emerald-50 text-emerald-700" : product.status === "archived" ? "bg-rose-50 text-rose-700" : "bg-orange-50 text-orange-700"}`}>{product.status}</span></div><div className="relative flex justify-end"><button type="button" disabled={busy === product.id} onClick={() => setOpenMenu(openMenu === product.id ? null : product.id)} className="icon-button border border-slate-200 dark:border-white/10" aria-label="Product actions" title="Product actions"><MoreHorizontal className="size-4" /></button>{openMenu === product.id && <div className="absolute right-0 top-11 z-30 w-44 rounded-xl border border-slate-200 bg-white p-1.5 shadow-xl dark:border-white/10 dark:bg-slate-900"><Link href={`/product/${product.slug}`} target="_blank" onClick={() => setOpenMenu(null)} className="flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold hover:bg-orange-50"><Eye className="size-3.5" /> View product</Link><Link href={`/admin/products/${product.id}/edit?shop=${shopId}`} onClick={() => setOpenMenu(null)} className="flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold hover:bg-orange-50"><Edit3 className="size-3.5" /> Edit product</Link>{["draft", "pending"].includes(product.status) && <button type="button" onClick={() => { setOpenMenu(null); void setStatus(product, "published"); }} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold text-emerald-700 hover:bg-emerald-50"><Check className="size-3.5" /> Approve product</button>}{product.status === "pending" && <button type="button" onClick={() => { setOpenMenu(null); void setStatus(product, "archived"); }} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold text-rose-600 hover:bg-rose-50"><X className="size-3.5" /> Reject product</button>}{product.status === "published" && <button type="button" onClick={() => { setOpenMenu(null); void setStatus(product, "archived"); }} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold text-rose-600 hover:bg-rose-50"><X className="size-3.5" /> Archive product</button>}{product.status === "archived" && <button type="button" onClick={() => { setOpenMenu(null); void setStatus(product, "published"); }} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold text-emerald-700 hover:bg-emerald-50"><Check className="size-3.5" /> Restore product</button>}</div>}</div></div>)}</div>}</section><Pagination total={filtered.length} page={pagination.page} pageSize={pagination.pageSize} totalPages={pagination.totalPages} onPageChange={pagination.setPage} onPageSizeChange={pagination.setPageSize} /></div>;
}
