"use client";

import { ExternalLink } from "lucide-react";
import Link from "next/link";
import { updateDeliveryAction } from "@/app/rider/actions";
import { Pagination, useUrlPagination } from "@/components/ui/pagination";

export type RiderDeliveryRow = { id: string; shopOrderId: string; shopName: string; status: string; amount: number; paymentMethod: string; assignedAt: string };
export function RiderDeliveriesTable({ rows, total }: { rows: RiderDeliveryRow[]; total?: number }) {
  const totalRows = total ?? rows.length;
  const pagination = useUrlPagination(totalRows);
  const visible = total === undefined ? rows.slice(pagination.from, pagination.to + 1) : rows;
  return <section data-pagination-list className={`surface w-full max-w-full overflow-hidden transition-opacity ${pagination.isPending ? "pointer-events-none opacity-60" : ""}`}><div className="hidden md:block"><table className="w-full table-fixed text-left text-sm"><colgroup><col className="w-[18%]" /><col className="w-[15%]" /><col className="w-[14%]" /><col className="w-[14%]" /><col className="w-[12%]" /><col className="w-[27%]" /></colgroup><thead className="border-b border-slate-100 bg-slate-50 text-[10px] uppercase tracking-[.12em] text-slate-500 dark:border-white/10 dark:bg-white/5"><tr><th className="px-3 py-4">Shop order</th><th className="px-3 py-4">Shop</th><th className="px-3 py-4">Amount</th><th className="px-3 py-4">Assigned</th><th className="px-3 py-4">Status</th><th className="px-3 py-4 text-right">Next action</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-white/10">{visible.map((row) => <DeliveryRow key={row.id} row={row} />)}</tbody></table></div><div className="grid gap-3 p-4 md:hidden">{visible.map((row) => <DeliveryCard key={row.id} row={row} />)}</div><div className="px-5 pb-4"><Pagination total={totalRows} page={pagination.page} pageSize={pagination.pageSize} totalPages={pagination.totalPages} onPageChange={pagination.setPage} onPageSizeChange={pagination.setPageSize} /></div></section>;
}

function DeliveryRow({ row }: { row: RiderDeliveryRow }) {
  const next = row.status === "assigned" ? "accepted" : row.status === "accepted" ? "picked_up" : row.status === "picked_up" ? "out_for_delivery" : row.status === "out_for_delivery" ? "delivered" : "";
  const completed = ["delivered", "failed", "cancelled"].includes(row.status);
  return <tr><td className="px-5 py-4"><Link href={`/rider/assignments/${row.id}`} className="font-black hover:text-orange-500">#{row.shopOrderId.slice(0, 8)} <ExternalLink className="inline size-3" /></Link><p className="mt-1 text-xs text-slate-400">{row.paymentMethod.replaceAll("_", " ")}</p></td><td className="px-5 py-4 font-semibold">{row.shopName}</td><td className="px-5 py-4 font-black">Rs. {row.amount.toLocaleString()}</td><td className="px-5 py-4 text-xs text-slate-500">{row.assignedAt}</td><td className="px-5 py-4"><span className="rounded-full bg-orange-50 px-2.5 py-1 text-[10px] font-black capitalize text-orange-700">{row.status.replaceAll("_", " ")}</span></td><td className="px-5 py-4 text-right">{next ? <form action={updateDeliveryAction} className="inline-flex items-center gap-2"><input type="hidden" name="assignmentId" value={row.id} /><input type="hidden" name="status" value={next} /><input type="hidden" name="collectedAmount" value={next === "delivered" ? row.amount : 0} /><button className="button-primary bg-orange-500 px-3 py-2 text-xs hover:bg-orange-600">{next === "accepted" ? "Accept" : next === "picked_up" ? "Mark picked up" : next === "out_for_delivery" ? "Start delivery" : "Mark delivered"}</button></form> : <span className="text-xs font-semibold text-slate-400">{completed ? "Completed" : "No action"}</span>}</td></tr>;
}

function DeliveryCard({ row }: { row: RiderDeliveryRow }) {
  const next = row.status === "assigned" ? "accepted" : row.status === "accepted" ? "picked_up" : row.status === "picked_up" ? "out_for_delivery" : row.status === "out_for_delivery" ? "delivered" : "";
  return <article className="rounded-2xl border border-slate-200 p-4 dark:border-white/10"><div className="flex items-start justify-between gap-3"><div><Link href={`/rider/assignments/${row.id}`} className="font-black hover:text-orange-500">#{row.shopOrderId.slice(0, 8)}</Link><p className="mt-1 text-xs text-slate-500">{row.shopName}</p></div><span className="rounded-full bg-orange-50 px-2.5 py-1 text-[10px] font-black capitalize text-orange-700">{row.status.replaceAll("_", " ")}</span></div><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><p className="text-slate-400">Amount</p><p className="mt-1 font-black">Rs. {row.amount.toLocaleString()}</p></div><div><p className="text-slate-400">Assigned</p><p className="mt-1 font-semibold">{row.assignedAt}</p></div></div>{next && <form action={updateDeliveryAction} className="mt-4"><input type="hidden" name="assignmentId" value={row.id} /><input type="hidden" name="status" value={next} /><input type="hidden" name="collectedAmount" value={next === "delivered" ? row.amount : 0} /><button className="button-primary w-full bg-orange-500 px-3 py-2.5 text-xs hover:bg-orange-600">{next === "accepted" ? "Accept" : next === "picked_up" ? "Mark picked up" : next === "out_for_delivery" ? "Start delivery" : "Mark delivered"}</button></form>}</article>;
}
